### ISSUE TITLE
Ajout d'un nouveau projet

### ISSUE THREAD

**Issue by AdrienCeschin** [houssembenali/fil_rouge#10]
**Description**
	En tant qu'administrateur je veux pouvoir ajouter un nouveau projet. 
	Je dois pouvoir renseigner les information essentielles sur ce projet (Nom du Projet, Url du Dépot GitHub, si le dépot est privé ou non, et si oui le Secret du Dépot).
	Je veux pouvoir réaliser cette action depuis un page d'ajout de projet.
	
**Critères d'acceptance**
- [x] Le menu est présent en haut de la page d'ajout de projet.
- [x] La page peut être accédée soit par l'élément "Ajouter un Projet".
- [x] Les champs suivants sont à renseigner : "Nom du Projet", "Url du Dépot GitHub", "Projet Privé", "Secret du GitHub".
- [x] Le Nom du Projet doit être unique.
- [x] Le Nom du Projet ne peut être composé que de caractères alphanumériques (minuscules et majuscules, au moins un), d'espaces et de tirets hauts et bas.
- [x] La longueur du Nom du Projet ne peut dépasser 30 caractères.
- [x] L'url du Dépot GitHub doit être valide (vérification de l'existence du dépot à la création du projet).
~~- [ ] Le champ "Projet Privé" ne peux accepter qu'une réponse booléenne, "oui" ou "non".~~
~~- [ ] Le champ "Secret du GitHub" n'est accessible que si la valeur rentrée pour le champ "Projet Privé" est "oui".~~
~~- [ ] La validité du secret doit être vérifiée à la création du projet.~~
- [x] Un bouton de validation de l'ajout de projet est disponible en bas de page. Son utilisation redirige sur la page de Liste des Projets.
- [x] Les ébauches graphiques de la page sont respectées.
	
NB : pour les tâches supprimer ➡️ Si le projet est privé le lien git doit êtres correct incluant le jeton exemple : https://[private_key]:x-oauth-basic@github.com/user/repo.git

**Tasks**
