### ISSUE TITLE
Supprimer un projet

### ISSUE THREAD

**Issue by AdrienCeschin** [houssembenali/fil_rouge#11]
**Description**
	En tant qu'administrateur je veux pouvoir supprimer un projet existant.
	Je veux pouvoir réaliser cette action depuis la page d'information du projet à supprimer.
	
**Critères d'acceptance**
- [x] Un bouton "Supprimer le Projet" est disponible en bas à droite de l'écran.
- [x] Un clic sur ce bouton entraîne la suppression du projet et de toutes ses information.
- [x] L'utilisateur est redirigé sur la page de Liste des Projets.
- [x] Une fois le projet supprimé il n'est plus possible d'accéder au projet, que ce soit par un lien sur la page de Liste des Projets ou par son url.
- [x] Une fois le projet supprimé, les pages web associées au projet ne sont plus accessibles par un navigateur.

**Tasks**

**Linked issue** 
- #7
