### ISSUE TITLE
Supprimer un projet depuis la page de Liste des Projets

### ISSUE THREAD

**Issue by AdrienCeschin** [houssembenali/fil_rouge#12]
**Description**
	En tant qu'administrateur je veux pouvoir supprimer un projet existant directement depuis la page de Liste des Projets.
	
**Critères d'acceptance**
- [x] Un bouton "Supprimer" est disponible à droite de l'écran, sur chaque ligne comportant le nom d'un projet sur la page Liste des Projets.
- [x] La page Liste des Projets respecte les ébauches graphiques fournies.
- [x] Un clic sur le bouton "Supprimer" entraîne la suppression du projet situé sur la même ligne.
- [x] La page de Liste des Projets se recharge pour présenter une liste de projets dans laquelle ne figure pas le projet supprimé.
- [x] Une fois le projet supprimé il n'est plus possible d'accéder au projet, que ce soit par un lien sur la page de Liste des Projets ou par son url.
- [x] Une fois le projet supprimé, les pages web associées au projet ne sont plus accessibles par un navigateur.

**Tasks**

**Linked issues**
- #3
- #11

**Comment by houssembenali** [comment]
Salut tous le monde après plusieurs tentative j'ai pas réussi a intégrer fontawsome pour gérer les icône SVG les plus populaire, j'ai essayer même a intégrer une image stocké en local et l'intégrer avec <img src="..."> mais sans sucée aussi, si quelqu'un connait un peux le sujet  sinon on dépasse et on part vers des sujet plus prioritaire.

**Comment by AdrienCeschin** [comment]
@houssembenali la description de la story a été mise à jour pour partir sur l'utilisation d'un bouton "Supprimer" plutôt que d'une "icône poubelle". Pas de soucis donc.

Par ailleurs est embarqué dans cette story la redirection de l'utilisateur (administrateur) vers la page de Liste des Projets lorsqu'il passe par l'url http://url-de-l-application (ajout lié à la story #5 )
