### ISSUE TITLE
Accessibilité des pages de sites depuis un navigateur web

### ISSUE THREAD

**Issue by AdrienCeschin** [houssembenali/fil_rouge#13]
**Description**
	En tant que rédacteur je veux que les pages de mon site soient accessibles librement sur un navigateur, sur une adresse spécifiée.

**Critères d'acceptance**
- [ ] En utilisant une url de la forme http://url-de-base/nom-de-mon-site/nom-de-page n'importe quel internaute doit pouvoir accéder à une page de mon site, correspondant à un des fichiers markdown (nommé nom-de-page.md) présent sur le dépôt GitHub communiqué aux administrateurs de l'application.
- [ ] En utilisant une url de la forme http://url-de-base/nom-de-mon-site n'importe quel internaute doit pouvoir accéder à une page récapitulant l'ensemble des pages de mon site, correspondant à une liste de l'ensemble des fichiers nom-de-page[i].md, sans l'extension ".md" présents sur le dépot GitHub communiqué aux administrateurs de l'application.
- [ ] Sur la page d'index de mon site, les noms des différentes pages sont des liens cliquables qui redirigent l'internaute vers la page correspondante.
	
**Tasks**
