### ISSUE TITLE
Présence d'une table des matières pour chaque page

### ISSUE THREAD

**Issue by AdrienCeschin** [houssembenali/fil_rouge#14]
**Description**
	En tant que rédacteur je veux qu'une fois publiées mes pages comportent une section "table des matières" en haut de page, permettant aux internautes de naviguer plus aisément au sein de la page.
	
**Critères d'acceptance**
- [x] Une table des matières regroupant tous les titres de ma page est présente.
- [x] Cette table des matières est le premier élément de la page.
- [x] Les tables de matière doivent avoir un titre nommé "SOMMAIRE"
~~- [ ] Si une table des matières est déjà présente dans les documents .md déposés sur mon compte GitHub je ne veux pas qu'une nouvelle table des matières vienne l'écraser.~~ (à éliminer !!!! ??)
	
**Tasks**

**Comment by houssembenali** [comment]
Salut tous le monde c'est un peux difficile a identifier si la page MD  a une table de matière ou non de façon automatique 😢 ❗  , donc je pense que c'est l'utilisateur 👤  qui doit choisir avoir une table de matière 📖  ou non via la checkbox ✅ .
sinon je suis ouvert a tous autres suggestions  😸
