### ISSUE TITLE
Tests de la qualité de l'application

### ISSUE THREAD

**Issue by AdrienCeschin** [houssembenali/fil_rouge#15]
**Description**
	En tant que propriétaire je veux que l'application livrée réponde à des critères de qualité de code et de fonctionnalité.
	
**Critères d'acceptance**
- [ ] La qualité du code et les bonnes pratiques de codage sont vérifiées pour faciliter la maintenabilité de l'application.
- [ ] Des tests de non régression sont joués afin de valider le bon fonctionnement de l'application.
- [ ] Les tests passent à plus de 90%.
- [ ] Les cas de tests en échec sont tracés et justifiés dans le PV de livraison. Des mesures sont prises dès la prochaine itération pour corriger ces échecs.

**Tasks**	

**Linked issues*
- #9
