### ISSUE TITLE
Tests de fiabilité de l'application

### ISSUE THREAD

**Issue by AdrienCeschin** [houssembenali/fil_rouge#16]
**Description**
	En tant que propriétaire, mon application étant accessible en ligne, je veux m'assurer qu'elle soit fiable.
	
**Critères d'acceptance**
- [ ] Des tests sont joués afin de s'assurer que l'application pourra supporter la charge d'utilisation.
- [ ] Des tests sont joués afin de s'assurer qu'il n'existe pas de faille de sécurité dans l'application, risquant de compromettre son fonctionnement ou celui des sites, de même que les données de nos clients.
- [ ] Les tests passent à plus de 90%.
- [ ] Les cas de tests en échec sont tracés et justifiés dans le PV de livraison. Des mesures sont prises dès la prochaine itération pour corriger ces échecs.

**Tasks**

**Linked issues**
- #15 
- #9
