### ISSUE TITLE
Mise en ligne de l'application

### ISSUE THREAD

**Issue by AdrienCeschin** [houssembenali/fil_rouge#17]
**Description**
	En tant qu'administrateur je veux pouvoir accéder à la plateforme de gestion de site de l'application depuis un navigateur web.
	
**Critères d'acceptance**
- [ ] L'application est accessible depuis un navigateur web via l'url http://url-de-mon-application
- [ ] Si je suis déjà connecté, en suivant l'url précédente on accède à la page de Liste des Projets.
- [ ] Si je ne suis pas déjà connecté, en suivant l'url précédente j'accède à la page d'authentification qui me redirigera automatiquement vers la page de Liste des Projets.
- [ ] Si je suis déjà connecté, en suivant l'url http://url-de-mon-application/page-spécifique j'accède à la page correspondante.
- [ ] Si je ne suis pas déjà connecté, en suivant l'url http://url-de-mon-application/page-spécifique j'accède à la page d'authentification qui me redirigera automatiquement vers la page correspondante.

**Tasks**

**Linked issues**
- #5 
- #2
