### ISSUE TITLE
Mise à jour des informations non secrètes d'un projet

### ISSUE THREAD

**Issue by AdrienCeschin** [houssembenali/fil_rouge#19]
**Description**
	En tant qu'administrateur je veux pouvoir modifier les valeurs du nom d'un projet, de l'url du dépot GitHub.
	Je veux pouvoir réaliser cette action champ par champ, depuis la page d'information projet.
	
**Critères d'acceptance**
- [ ] Un bouton "Modifier" est présent à côté de la valeur affectée au champ "Nom du Projet" et du champ "Url du Dépot GitHub".
- [ ] En appuyant sur le bouton "Modifier" un espace de saisie remplace l'affichage de la valeur du champ.
- [ ] L'espace de saisie est pré-rempli par la valeur déjà connue de ce champ.
- [ ] Les conditions appliquées aux valeurs de champs pour qu'elles soient valides sont les mêmes que pour la création d'un nouveau projet (Nom unique, dépot GitHub valide).
- [ ] Pendant l'édition d'un champ le bouton "Modifier" devient un bouton "Valider". Un bouton "Abandonner" apparaît à côté du bouton "Valider", qui permet d'annuler la mise à jour du champ.
- [ ] Un appui sur le bouton "Valider" fait disparaître l'espace de saisie et affiche la nouvelle valeur entrée.
- [ ] Un appui sur le bouton "Valider" lorsque la nouvelle valeur du champ n'est pas valide entraîne l'affichage d'un message d'erreur "Valeur non valide".
- [ ] Un appui sur le bouton "Abandonner" fait disparaître l'espace de saisie et affiche l'ancienne valeur du champ. Le bouton "Modifier" est de nouveau affiché, les deux boutons "Modifier" et "Abandonner" disparaissent.
	
**Tasks**

**Linked issues**
- #7
