### ISSUE TITLE
Panneau de log in pour les administrateurs

### ISSUE THREAD

**Issue by AdrienCeschin** [houssembenali/fil_rouge#2]
**Description**

En tant qu'administrateur je veux pouvoir me logger à l'application lorsque je rentre une url de l'application dans un navigateur web.
Toutes les urls de l'application doivent rediriger vers le panneau de log in si l'utilisateur n'est pas déjà connecté.
Le panneau doit comprendre deux champs : un champ pour le username et un champ pour le mot de passe.
Si l'un des deux champs est mal rempli l'authentification doit échouer et l'utilisateur peut retenter de se logger.

En tant qu'utilisateur je veux pouvoir m'enregistrer sur l'application pour pouvoir me connecter ultérieurement en tant qu'administrateur.

**Critères d'acceptance**

- [x] On ne doit pas pouvoir accéder à l'application sans passer par l'écran de log in
- [x] Sur la page de login deux champs doivent être remplis : name et password
- [x] Si l'un des deux n'est pas bon l'authentification échoue
- [x] Les names ou password vides ne sont pas acceptés
- [x] Les names et password n'acceptent que des caractères étant des : lettres (majuscules ou minuscules), des chiffres, des tirets hauts ou bas
- [x] Les utilisateurs n'ont pas de limite au nombre d'essais pour s'authentifier
- [x] Un bouton "Se Connecter" est disponible pour valider la saisie du name et password
- [x] L'utilisation de la touche "entrée" est équivalente à l'utilisation du bouton "Se Connecter"
- [x] La page doit respecter les ébauches graphiques fournies
- [x] Sur la page d'enregistrement trois champs doivent être remplis : email, name et password
- [x] Si l'email ou le name correspondent à un utilisateur déjà existant l'enregistrement échoue et un message d'erreur est affiché
- [x] Les names ou passwords vides ne sont pas acceptés
- [x] Les names et passwords n'acceptent que des caractères étant des : lettres (majuscules ou minuscules), des chiffres, des tirets hauts ou bas
- [x] Les emails doivent respecter un format d'email
- [x] Un bouton "Sign Up" est disponible pour valider la saisie de l'email, du name et du password
- [x] La page respecte les ébauches graphiques fournies
	
**Tasks**
