### ISSUE TITLE
Mise à jour systématique de l'application en ligne

### ISSUE THREAD

**Issue by AdrienCeschin** [houssembenali/fil_rouge#20]
**Description**
	En tant que propriétaire de l'application je veux que chaque nouvelle fonctionnalité terminée (user story) soit directement disponible sur la version de l'application accessible en ligne.
	
**Critères d'acceptance**
- [ ] A chaque fois qu'une user story est terminée, une nouvelle version "provisoire" de l'application est générée.
- [ ] Si les critères de tests (plus de 90% de tests passés) sont remplis, la nouvelle version "provisoire" de l'application remplace celle déjà en ligne.
- [ ] A chaque fin de sprint la version "livrée" de l'application remplace celle déjà en ligne.
- [ ] Toutes les versions "provisoire" de l'application sont livrées, pour traçabilité, sans PV ni BL mais avec un rapport de tests.
- [ ] La nomenclature des dossier contenant les applications provisoires est la suivante : nom-de-l-application_version-de-l-application_SNAPSHOT_numéro-de-la-user-story-livrée.

**Tasks**

**Linked issues**
- #9 
- #17
