### ISSUE TITLE
Monitorer le fonctionnement de la plateforme de production

### ISSUE THREAD

**Issue by AdrienCeschin** [houssembenali/fil_rouge#21]
**Description**
        En tant qu'administrateur je veux peux pouvoir vérifier par des logs le bon fonctionnement et les performances des solutions utilisées dans le déploiement de l'application sur sa plateforme de production.

**Critères d'acceptance**
- [ ] Une nouvelle section "Monitoring" est disponible sur l'interface graphique de l'application.
- [ ] Un élément "Monitoring" est ajouté au menu de navigation.
- [ ] On accède à cette page par url à l'adresse suivante : http://url-de-l-application/monitoring
- [ ] Si l'utilisateur n'est pas connecté il est d'abord redirigé vers la page d'authentification. Si l'authentification réussit il est redirigé vers la page "Monitoring".
- [ ] On retrouve sur cette page les logs du cloud relatifs au fonctionnement de l'application.
- [ ] On retrouve sur cette page les logs du cloud relatifs à l'accès et au stockage des sites web.
- [ ] On retrouve sur cette page les logs relatifs aux orchestrateurs et conteneurs utilisés pour le déploiement de l'application.

**Tasks**
