### ISSUE TITLE
Etudes préparatoire - Sprint 2

### ISSUE THREAD

**Issue by AdrienCeschin** [houssembenali/fil_rouge#23]
**Description**
Suite de taches internes préparatoires au sprint planning pour le sprint 2 et au développements qui seront réalisés au cours de ce sprint.

**Tasks**
- [ ] Intégrer des tests de qualité au pipeline Jenkins (PyLint, Flake8 ?)
- [ ] Intégrer un linter aux IDE pour limiter les alertes lors du passage des tests de qualité.
- [ ] Intégrer les tests unitaires au pipeline Jenkins (unittest, PyUnit ?)
- [ ] Intégrer les tests fonctionnels au pipeline Jenkins (Multi-Mechanize ?)
