### ISSUE TITLE
Bouton de Déconnexion de l'application dans le menu

### ISSUE THREAD

**Issue by AdrienCeschin** [houssembenali/fil_rouge#24]
**Description**
En tant qu'administrateur, lorsque je suis connecté au site de gestion des projets, je veux pouvoir me déconnecter du site de gestion des projets depuis n'importe quelle page. Je veux pouvoir le faire à l'aide d'un bouton présent dans le menu de navigation.

**Critères d'acceptance**

- [x] Un bouton "Déconnexion" est disponible sur la droite du menu de navigation (voir US #4 ).
- [ ] Un clic sur le bouton "Déconnexion" redirige l'utilisateur vers la page de log in.
- [ ] Lorsque l'utilisateur est redirigé vers la page de log in depuis une page spécifique après utilisation du bouton "Déconnexion", s'il réussit à se connecter de nouveau il doit être directement redirigé vers la page d'accueil (page de "Liste des projets" pour l'instant).
- [ ] Si l'utilisateur est en train de saisir des information sur une page (page "Ajout de projet" ou "Paramétrage" par exemple) au moment où il utilise le bouton "Déconnexion" il est déconnecté sans message d'avertissement.

**Tasks**

**Linked issues**

- #2 
- #4 
- #17
