### ISSUE TITLE
Affichage de la liste des projets gérés par l'application

### ISSUE THREAD

**Issue by AdrienCeschin** [houssembenali/fil_rouge#3]
**Description**

En tant qu'administrateur, une fois connecté, je veux pouvoir visualiser une liste de tous les projets gérés par l'application, et pour accéder aux paramètres de chacun.
	
**Critères d'acceptance**

- [x] Chaque projet occupe une ligne
- [x] L'ensemble des projets gérés par l'application est affiché
- [x] Si le nombre de projets est trop important pour tenir sur un seul écran, une barre de scroll doit apparaître sur la droite de l'écran.
- [x] On doit pouvoir monter et descendre dans la page, soit à l'aide de la barre de scroll, soit à l'aide des flèches "haut" et "bas" du clavier.
- [x] Chaque projet est représenté par son attribut nom.
- [x] Chaque nom de projet est un lien cliquable qui renvoie vers une page d'information du projet.
- [x] La page respecte les ébauches graphiques fournies.

**Tasks**

- [ ] Affichage des projets
- [ ] Gérer la navigation dans la page
- [ ] Mettre en place l'aspect graphique
- [ ] Rédiger la documentation
