### ISSUE TITLE
Affichage d'un menu de navigation

### ISSUE THREAD

**Issue by AdrienCeschin** [houssembenali/fil_rouge#4]
**Description**
	En tant qu'administrateur je veux pouvoir circuler dans les différentes pages de l'interface graphique de l'application à l'aide d'un menu situé en haut de page.
	
**Critères d'acceptance**
- [x] Le menu est présent sur toutes les pages de l'interface graphique de l'application.
- [x] Le menu est le premier élément en haut de page, il respecte les ébauches graphiques fournies.
- [x] Le menu contient cinq éléments : "GitHoster", "Liste des projets", "Ajouter un projet", "Paramétrage" (qui sont alignés à gauche du menu) et "Déconnexion" (qui est aligné à droite du menu).
- [x] L'élément "GitHoster" renvoie vers la page d'accueil du menu (pour l'instant, page de "Liste des projets").
- [x] L'élément "Déconnexion" n'est pas fonctionnel (il sera pris en charge dans une story suivante).
- [x] Les trois éléments du menu ("Liste des projets", "Ajouter un projet" et "Paramétrage") sont des liens cliquables qui renvoient vers la page correspondante de l'interface graphique de l'application.
- [x] L'élément du menu correspondant à la page actuellement consultée est affiché en gras.

**Tasks**

**Comment by houssembenali** [comment]
Salut @arnauddegez les 4 première tache a été implémenter dans l'US3 #3 et valider dans la pull request #32.
il reste la dernière tâche  que je suis entraient de l'implémenter.
merci
