### ISSUE TITLE
Accès aux pages de l'interface graphique par url

### ISSUE THREAD

**Issue by AdrienCeschin** [houssembenali/fil_rouge#5]
**Description**
	En tant qu'administrateur je veux pouvoir naviguer dans les différentes pages de l'interface graphique en entrant directement les bonnes urls.

**Critères d'acceptance**
- [x] L'url renvoie directement vers la page idoine.
- [x] Si l'url correspond à une page de projet qui n'existe plus l'utilisateur est redirigé automatiquement vers la page de liste des projets.
- [x] L'url de l'application est la suivante : http://url-de-l-application
- [x] L'url de la page de Liste des Projets est la suivante : http://url-de-l-application/ _liste-projets_
- [x] L'url de la page de paramétrage du cloud est la suivante : http://url-de-l-application/ _parametrage-cloud_
- [x] L'url de la page de création d'un projet est la suivante : http://url-de-l-application/ _nouveau-projet_

**Tasks**
