### ISSUE TITLE
Affichage des pages d'information projet

### ISSUE THREAD

**Issue by AdrienCeschin** [houssembenali/fil_rouge#7]
**Description**
	En tant qu'administrateur je veux pouvoir inspecter pour chaque projet géré par l'application ses caractéristiques. 
	
**Critères d'acceptance**
- [ ] L'url de ces pages d'information projet doit être la suivante : http://url-de-l-application/liste-projets/ _$NOM-DU-PROJET_
- [ ] Le menu est l'élément le plus en haut de page.
- [ ] Les champs suivants sont indiqués : "Nom du Projet", "Url du Dépot GitHub", "Projet Privé", "Secret du GitHub".
- [ ] Le secret du GitHub ne doit pas être indiqué en clair.
- [ ] Un bouton doit être accessible pour permettre à l'administrateur de demander à recevoir par mail le secret du GitHub associé à un projet.
- [ ] La page doit respecter les ébauches graphiques fournies.

**Tasks**
