### ISSUE TITLE
Paramétrage du stockage cloud des pages html

### ISSUE THREAD

**Issue by AdrienCeschin** [houssembenali/fil_rouge#8]
**Description**
	En tant qu'administrateur je veux pouvoir spécifier le nom du bucket S3 qui sera utilisé pour stocker les pages html des sites et les rendre accessibles sur un navigateur.
	
**Critères d'acceptance**
- [x] Le menu est présent en haut de la page de paramétrage.
- [x] La page peut être accédée soit par l'élément "Paramétrage" dans le menu, soit par son url.
- [x] Un champ de saisie est disponible pour renseigner le nom du bucket S3.
- [x] Un bouton "ok" est disponible en bas de page pour valider le nom saisi.
- [x] Un clic sur le bouton "ok" entraine la mise à jour du nom du bucket, ou son ajout s'il n'est pas déjà connu. L'utilisateur est redirigé sur la page de "Liste des Projets".
- [x] Les ébauches graphiques de la page sont respectées.
- [x] Les noms autorisés pour les buckets respectent les règles de nommage des buckets sur Amazon Web Service (de 3 à 63 caractères, commencent et se terminent par des caractères alphanumériques, ne contiennent que des minuscules, des chiffres, de points et des tirets hauts (-).
- [x] Le champ de saisie est pré-rempli par le nom actuel du bucket. Si le bucket n'a pas encore été créé ou si le fichier dans lequel le nom est stocké n'existe pas ou n'est pas accessible, aucune vrai nom de pré-rempli le champ, seul un placeholder disant "nom du bucket" est affiché.
- [x] Les critères de validité des noms de buckets sont mentionnés sous forme de liste au dessus du champ de saisie.

**Tasks**

**Comment by michaelparfait** [comment]
Les règles suivantes s'appliquent pour nommer les compartiments dans Amazon S3 :

Les noms de buckets doivent comporter entre 3 et 63 caractères.

Les noms de compartiment ne peuvent être constitués que de lettres minuscules, de chiffres, de points (.) et de tirets (-).

Les noms de buckets doivent commencer et se terminer par une lettre ou un chiffre.
