### ISSUE TITLE
Livraison de l'application

### ISSUE THREAD

**Issue by AdrienCeschin** [houssembenali/fil_rouge#9]
**Description**
	En tant que propriétaire de l'application je veux pouvoir avoir accès aux différentes versions livrées de l'application.
	
**Critères d'acceptance**
- [x] L'accès à la solution de stockage des versions de l'application est sécurisé. Les accès ne sont connus que de l'équipe agile.
- [x] Toutes les versions de l'application sont accessibles sans limite de temps sur cette solution de stockage.
- [x] Le versionning de l'application respectera la norme suivante : nom-de-l-application_01.XX.YY où "XX" correspond à la version de la release (numéro du sprint) et YY à la numérotation de la version corrective de cette livraison.
- [ ] Une version utilisable de l'application est livrée dans un dossier répondant à la convention précédente. Sont également livrés avec l'application un PV de livraison (dans lequel figurera un rapport sur les campagnes de tests réalisées pour cette livraison) et un BL.

**Tasks**
